import { Category } from './types';

export const defaultCategories: Category[] = [
  {
    key: 'unknown',
    name: 'Unknown',
    description: 'Unknown',
    color: '#858585',
    isRoot: true,
  },
  {
    key: 'rent',
    name: 'Rent',
    description: 'Rental',
    color: '#594c07',
    isRoot: true,
  },
  {
    key: 'groceries',
    name: 'Groceries',
    description: 'Food and household items',
    color: '#52c41a',
    isRoot: true,
  },
  {
    key: 'groceries/bread',
    name: 'Groceries (Bread)',
    description: 'Bread',
    color: '#52c41a',
  },
  {
    key: 'groceries/others',
    name: 'Groceries (Others)',
    description: 'Normal groceries, etc.',
    color: '#52c41a',
  },
  {
    key: 'household',
    name: 'Household',
    description: 'Household',
    color: '#52c41a',
    isRoot: true,
  },
  {
    key: 'household/appliances',
    name: 'Appliances',
    description: 'Household appliances',
    color: '#52c41a',
  },
  {
    key: 'household/others',
    name: 'Other household',
    description: 'Other household items',
    color: '#52c41a',
  },
  {
    key: 'health',
    name: 'Health',
    description: 'Products and activities related to health',
    color: '#f821ce',
    isRoot: true,
  },
  {
    key: 'insurance',
    name: 'Insurance',
    description: 'Life, travel, etc. insurance',
    color: '#7a3213',
    isRoot: true,
  },
  {
    key: 'food',
    name: 'Food',
    description: 'Food',
    color: '#52c41a',
    isRoot: true,
  },
  {
    key: 'food/eating-out',
    name: 'Food (Eating Out)',
    description: 'Eating out',
    color: '#52c41a',
  },
  {
    key: 'food/snacks',
    name: 'Food (Snacks)',
    description: 'Eating out - snacks',
    color: '#52c41a',
  },
  {
    key: 'food/drinks',
    name: 'Food (Drinks)',
    description: 'Eating out - drinks',
    color: '#52c41a',
  },
  {
    key: 'food/delivery',
    name: 'Food (Delivery)',
    description: 'Food deliveries',
    color: '#52c41a',
  },
  {
    key: 'food/others',
    name: 'Food (Others)',
    description: 'Other food stuff',
    color: '#52c41a',
  },
  {
    key: 'transport',
    name: 'Transport',
    description: 'Transport',
    color: '#1890ff',
    isRoot: true,
  },
  {
    key: 'transport/public',
    name: 'Transport (Public)',
    description: 'Bus / MRT',
    color: '#1890ff',
  },
  {
    key: 'transport/private',
    name: 'Transport (Private)',
    description: 'Taxi, Grab',
    color: '#1890ff',
  },
  {
    key: 'transport/cycling',
    name: 'Transport (Cycling)',
    description: 'Bike-sharing',
    color: '#1890ff',
  },
  {
    key: 'transport/others',
    name: 'Transport (Others)',
    description: 'Other transport',
    color: '#1890ff',
  },
  {
    key: 'education',
    name: 'Education',
    description: 'Courses, books, etc. for adults and kids',
    color: '#a229aa',
    isRoot: true,
  },
  {
    key: 'education/adults',
    name: 'Education (Adults)',
    description: 'Courses, books, etc. for adults',
    color: '#a229aa',
  },
  {
    key: 'education/kids',
    name: 'Education (Kids)',
    description: 'Courses, books, etc. for kids',
    color: '#a229aa',
  },
  {
    key: 'education/toys-books',
    name: 'Education (Toys & books)',
    description: 'Toys, books, etc. for kids.',
    color: '#a229aa',
  },
  {
    key: 'education/others',
    name: 'Education (Others)',
    description: 'Other educational stuff',
    color: '#a229aa',
  },
  {
    key: 'entertainment',
    name: 'Entertainment',
    description: 'Entertainment',
    color: '#722ed1',
    isRoot: true,
  },
  {
    key: 'entertainment/playground',
    name: 'Entertainment (Playground)',
    description: 'Playground',
    color: '#722ed1',
  },
  {
    key: 'entertainment/movies',
    name: 'Entertainment (Movies)',
    description: 'Movies',
    color: '#722ed1',
  },
  {
    key: 'entertainment/others',
    name: 'Entertainment (Others)',
    description: 'Other entertainment',
    color: '#722ed1',
  },
  {
    key: 'shopping',
    name: 'Shopping',
    description: 'All shopping',
    color: '#02efe8',
    isRoot: true,
  },
  {
    key: 'shopping/beauty',
    name: 'Shopping (Beauty)',
    description: 'Cosmetics stuff',
    color: '#02efe8',
  },
  {
    key: 'shopping/gifts',
    name: 'Shopping (Gifts)',
    description: 'Gifts for others',
    color: '#02efe8',
  },
  {
    key: 'shopping/online',
    name: 'Shopping (Online)',
    description: 'Uncategorized stuff bought online.',
    color: '#02efe8',
  },
  {
    key: 'shopping/offline',
    name: 'Shopping (Offline)',
    description: 'Uncategorized stuff bought in retail stores.',
    color: '#02efe8',
  },
  {
    key: 'software',
    name: 'Software and subscriptions',
    description: 'Software subscriptions like Google photos, storage, etc.',
    color: '#5f8298',
    isRoot: true,
  },
  {
    key: 'party',
    name: 'Party expenses',
    description: 'Expenditure for parties',
    color: '#d3bc28',
    isRoot: true,
  },
  {
    key: 'holiday',
    name: 'Holiday expenses',
    description: 'Expenditure during holidays',
    color: '#d3bc28',
    isRoot: true,
  },
  {
    key: 'holiday/accom',
    name: 'Holiday expenses (Accommodation)',
    description: 'Accommodation',
    color: '#d3bc28',
  },
  {
    key: 'holiday/flights',
    name: 'Holiday expenses (Flights)',
    description: 'Flights',
    color: '#d3bc28',
  },
  {
    key: 'holiday/others',
    name: 'Holiday expenses (Others)',
    description: 'Other expenditure during holidays',
    color: '#d3bc28',
  },
  {
    key: 'utilities',
    name: 'Utilities',
    description: 'Electricity, water, internet',
    color: '#fa8c16',
    isRoot: true,
  },
  // {
  //   key: 'clothes',
  //   name: 'Clothes',
  //   description: 'Clothes',
  //   color: '#bc0d0d',
  // },
  {
    key: 'loans',
    name: 'Loans',
    description: 'Loan repayments, etc.',
    color: '#bc0d0d',
    isRoot: true,
  },
  // {
  //   key: 'interest',
  //   name: 'Interest',
  //   description: 'Interest on loans, etc.',
  //   color: '#bc0d0d',
  //   isRoot: true,
  // },
  {
    key: 'donations',
    name: 'Donations',
    description: 'GIVING.SG, etc.',
    color: '#bc0d0d',
    isRoot: true,
  },
  {
    key: 'scams',
    name: 'Scams',
    description: 'Scams',
    color: '#bc0d0d',
    isRoot: true,
  },
  {
    key: 'government',
    name: 'Government bills',
    description: 'Tax, ICA, MOM, etc.',
    color: '#bc0d0d',
    isRoot: true,
  },
  {
    key: 'others',
    name: 'Others',
    description: 'Others',
    color: '#bc0d0d',
    isRoot: true,
  },
  {
    key: 'others/fees',
    name: 'Other fees',
    description: 'Annual membership fees, etc.',
    color: '#bc0d0d',
  },
];
