import { Category } from './types';

export const defaultCategories: Category[] = [
  {
    key: 'rent',
    name: 'Rent',
    description: 'Rental',
    color: '#594c07',
  },
  {
    key: 'groceries',
    name: 'Groceries',
    description: 'Food and household items',
    color: '#52c41a',
  },
  {
    key: 'groceries-bread',
    name: 'Groceries (Bread)',
    description: 'Bread',
    color: '#52c41a',
  },
  {
    key: 'household-appliances',
    name: 'Appliances',
    description: 'Household appliances',
    color: '#52c41a',
  },
  {
    key: 'household-other',
    name: 'Other household',
    description: 'Other household items',
    color: '#52c41a',
  },
  {
    key: 'health',
    name: 'Health',
    description: 'Products and activities related to health',
    color: '#f821ce',
  },
  {
    key: 'insurance',
    name: 'Insurance',
    description: 'Life, travel, etc. insurance',
    color: '#7a3213',
  },
  {
    key: 'food',
    name: 'Food',
    description: 'Food',
    color: '#52c41a',
  },
  {
    key: 'food-eating-out',
    name: 'Food (Eating Out)',
    description: 'Eating out',
    color: '#52c41a',
  },
  {
    key: 'food-snacks',
    name: 'Food (Snacks)',
    description: 'Eating out - snacks',
    color: '#52c41a',
  },
  {
    key: 'food-drinks',
    name: 'Food (Drinks)',
    description: 'Eating out - drinks',
    color: '#52c41a',
  },
  {
    key: 'food-delivery',
    name: 'Food (Delivery)',
    description: 'Food deliveries',
    color: '#52c41a',
  },
  {
    key: 'transport',
    name: 'Transport',
    description: 'Transport',
    color: '#1890ff',
  },
  {
    key: 'transport-public',
    name: 'Transport (Public)',
    description: 'Bus / MRT',
    color: '#1890ff',
  },
  {
    key: 'transport-private',
    name: 'Transport (Private)',
    description: 'Taxi, Grab',
    color: '#1890ff',
  },
  {
    key: 'transport-cycling',
    name: 'Transport (Cycling)',
    description: 'Bike-sharing',
    color: '#1890ff',
  },
  {
    key: 'education',
    name: 'Education',
    description: 'Courses, books, etc. for adults and kids',
    color: '#a229aa',
  },
  {
    key: 'education-adults',
    name: 'Education (Adults)',
    description: 'Courses, books, etc. for adults',
    color: '#a229aa',
  },
  {
    key: 'education-kids',
    name: 'Education (Kids)',
    description: 'Courses, books, etc. for kids',
    color: '#a229aa',
  },
  {
    key: 'entertainment',
    name: 'Entertainment',
    description: 'Entertainment',
    color: '#722ed1',
  },
  {
    key: 'entertainment-playground',
    name: 'Entertainment (Playground)',
    description: 'Playground',
    color: '#722ed1',
  },
  {
    key: 'entertainment-movies',
    name: 'Entertainment (Movies)',
    description: 'Movies',
    color: '#722ed1',
  },
  {
    key: 'entertainment-others',
    name: 'Entertainment (Others)',
    description: 'Other entertainment',
    color: '#722ed1',
  },
  {
    key: 'kids-toys-books',
    name: 'Toys and books (Kids)',
    description: 'Toys, books, etc. for kids.',
    color: '#ff84fd',
  },
  {
    key: 'shopping',
    name: 'Shopping',
    description: 'All shopping',
    color: '#02efe8',
  },
  {
    key: 'shopping-beauty',
    name: 'Shopping (Beauty)',
    description: 'Cosmetics stuff',
    color: '#02efe8',
  },
  {
    key: 'shopping-gifts',
    name: 'Shopping (Gifts)',
    description: 'Gifts for others',
    color: '#02efe8',
  },
  {
    key: 'shopping-online',
    name: 'Shopping (Online)',
    description: 'Uncategorized stuff bought online.',
    color: '#02efe8',
  },
  {
    key: 'shopping-offline',
    name: 'Shopping (Offline)',
    description: 'Uncategorized stuff bought in retail stores.',
    color: '#02efe8',
  },
  {
    key: 'software',
    name: 'Software and subscriptions',
    description: 'Software subscriptions like Google photos, storage, etc.',
    color: '#5f8298',
  },
  {
    key: 'party',
    name: 'Party expenses',
    description: 'Expenditure for parties',
    color: '#d3bc28',
  },
  {
    key: 'holiday',
    name: 'Holiday expenses',
    description: 'Expenditure during holidays',
    color: '#d3bc28',
  },
  {
    key: 'holiday-accom',
    name: 'Holiday expenses (Accommodation)',
    description: 'Accommodation',
    color: '#d3bc28',
  },
  {
    key: 'holiday-flights',
    name: 'Holiday expenses (Flights)',
    description: 'Flights',
    color: '#d3bc28',
  },
  {
    key: 'holiday-others',
    name: 'Holiday expenses (Others)',
    description: 'Other expenditure during holidays',
    color: '#d3bc28',
  },
  {
    key: 'utilities',
    name: 'Utilities',
    description: 'Electricity, water, internet',
    color: '#fa8c16',
  },
  {
    key: 'clothes',
    name: 'Clothes',
    description: 'Clothes',
    color: '#bc0d0d',
  },
  {
    key: 'loans',
    name: 'Loans',
    description: 'Loan repayments, etc.',
    color: '#bc0d0d',
  },
  {
    key: 'donations',
    name: 'Donations',
    description: 'GIVING.SG, etc.',
    color: '#bc0d0d',
  },
  {
    key: 'scams',
    name: 'Scams',
    description: 'Scams',
    color: '#bc0d0d',
  },
  {
    key: 'government',
    name: 'Government bills',
    description: 'Tax, ICA, MOM, etc.',
    color: '#bc0d0d',
  },
  {
    key: 'interest',
    name: 'Interest',
    description: 'Interest on loans, etc.',
    color: '#bc0d0d',
  },
  {
    key: 'others-fees',
    name: 'Other fees',
    description: 'Annual membership fees, etc.',
    color: '#bc0d0d',
  },
];
